product-os/jellyfish-worker

.github/renovate.json
=> Renovate: Add resinci/jellyfish-test group

lib/index.ts
due to async/await using variables to cache these is not safe and
can lead to loss of those when inserting many in paralel
this should fix https://github.com/product-os/jellyfish/pull/7175
=> fix race-condition when inserting worker types

@types/errio.d.ts, jest.config.js, lib/cards/create.ts, lib/cards/index.ts, lib/cards/triggered-action.ts, lib/cards/update.ts, lib/errors.ts, lib/index.spec.ts, lib/index.ts, lib/transformers.spec.ts, lib/transformers.ts, lib/triggers.spec.ts, lib/triggers.ts, lib/types.ts, lib/utils.spec.ts, lib/utils.ts, test/integration/execute.spec.ts, test/integration/index.spec.ts, test/integration/insert-card.spec.ts, test/integration/subscriptions.spec.ts, test/integration/trigger-updates.spec.ts, test/integration/triggers.spec.ts, test/integration/utils.spec.ts, test/integration/utils.ts
=> Remove license headers

.github/workflows/publish-docs.yml
=> Remove npm token step from docs action

lib/index.spec.ts, lib/index.ts
This should resolve the confusion that the current behavior has caused with users
=> let 1.x.y Transformers overwrite 0.x.y versions

package.json
=> Missed one peer-dependency from the last PR

lib/index.ts
=> Export `actions` properly

lib/index.ts
=> Export `IntegrationDefinition`

lib/sync/oauth.spec.ts, lib/sync/oauth.ts
=> Make passing oauth scopes optional

lib/sync/types.ts
=> Allow async isEventValid

lib/types.ts
=> Export the `request` argument of `Action.handler` and `Action.pre` as separate types

lib/index.ts, lib/sync/index.ts
=> Export SequenceItem type

lib/test-utils.ts
---
Breaking changes, but will only affect translate tests. Simplifying arguments and setting as many types as possible.
=> Update translate test function options/types

lib/sync/index.ts, lib/sync/types.ts
=> Fix whoami types

lib/index.ts, lib/sync/index.ts
=> Export sync errors

lib/test-utils.ts
=> Add retry to test-utils

lib/test-utils.ts
=> Allow regexp in base url (webhookScenario)

lib/errors.ts
=> Export sync errors alongside worker errors

lib/index.ts, lib/sync/index.ts
=> Export `sync/oauth`

lib/test-utils.ts
=> Add translateAfterAll

docker-compose.yml
=> Optimize postgres for tests

docker-compose.test.yml
=> Set LOGLEVEL=error for sut

lib/test-utils.ts
=> ACTUALLY import from the root of `js-combinatorics`

lib/index.ts, package.json
=> Fix bug where log context ends up with an additional object wrapper

lib/sync/instance.ts, lib/sync/types.ts
=> Sync: Improve typings for SyncContext.getActorId

lib/sync/types.ts
=> Sync: Add type declaration for actor first and last name

lib/index.ts
=> Fix execute success data checks

lib/contracts/index.ts, lib/contracts/view-scheduled-actions.ts
=> Add scheduled actions view

package.json
=> Bump internal jellyfish dependencies

package.json
=> Update cron-parser from 4.2.0 to 4.2.1

package.json
=> Bump core and queue

package.json
=> Update skhema from 6.0.3 to 6.0.6

package.json
=> Update @balena/jellyfish-core from 16.0.7 to 16.0.9

package.json
=> Update @balena/jellyfish-jellyscript from 5.2.1 to 5.2.2

lib/plugin/plugin.ts
=> Replace cardMixins with contractMixins

lib/contracts/mixins/as-pipeline-item.ts, lib/contracts/mixins/index.ts, lib/contracts/mixins/with-events.ts, lib/index.ts, package.json, test/unit/mixins.spec.ts
=> Add pipeline and events mixins

package.json, test/integration/contracts/mixins/with-events.spec.ts
=> Add events mixin formula test

README.md
=> Update usage example in readme

lib/actions/action-create-event.ts, lib/index.ts, lib/queue/events.ts, lib/queue/producer.ts, lib/triggers.ts, lib/utils.ts
=> A bit more cleanup

test/integration/index.spec.ts
=> Remove unnecessary test logs

lib/actions/action-matchmake-task.ts, lib/actions/index.ts, lib/contracts/generic-source.ts, lib/contracts/image-source.ts, lib/contracts/image.ts, lib/contracts/index.ts, lib/contracts/role-transformer-worker.ts, lib/contracts/service-source.ts, lib/contracts/task.ts, lib/contracts/transformer-merge-properties.ts, lib/contracts/transformer-worker.ts, lib/contracts/transformer.ts, lib/contracts/triggered-action-matchmake-task.ts, lib/contracts/triggered-action-merge-draft-version.ts, lib/contracts/view-all-transformer-types.ts, lib/contracts/view-all-transformer-workers.ts, lib/contracts/view-all-transformers.ts, lib/index.ts, test/integration/execute.spec.ts
Move transformer contracts from plugin-product-os.
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-product-os/pull/777
- https://github.com/product-os/jellyfish-plugin-default/pull/1106
- https://github.com/product-os/jellyfish-plugin-github/pull/836
- https://github.com/product-os/jellyfish/pull/8467
=> Add transformer contracts

test/integration/index.spec.ts
Add test to assert that the worker instance
is kept up-to-date when new transformer
contracts are added to the system.
=> Add transformer stream update test

lib/index.ts, lib/transformers.ts
=> Add transformer execution logs

lib/transformers.ts
=> Update transformer logs

lib/index.ts, lib/transformers.ts
=> Improve transformer logs

test/integration/insert-card.spec.ts
Add insertCard collision tests
Signed-off-by: YingwenChen yingwenchen@balena.io
=> Add insertCard collision tests 

lib/index.ts
=> Log execute session

lib/index.ts
=> Add another execute log

lib/index.ts
=> Update triggered action enqueue log

lib/index.ts
=> Use session actor for triggered actions

test/integration/execute.spec.ts
Add test that asserts that the actor used to
execute triggered action requests is the
actor of the session used to insert the
contract that caused the trigger.
=> Add triggered-action actor test

test/integration/execute.spec.ts
=> Update triggered action actor test

test/integration/actions/action-create-card.spec.ts
=> Add action-create-card duplicate slug test

lib/sync/index.ts, lib/sync/instance.spec.ts, lib/sync/instance.ts, lib/sync/pipeline.ts, lib/sync/types.ts
Token contains not only oauth app id and app secret, but also private key for encryption.
=> Add back token

lib/contracts/agent-settings.ts
=> Allow for empty agent-settings contracts

lib/index.ts, test/integration/actions/action-create-event.spec.ts, test/integration/index.spec.ts, test/integration/insert-card.spec.ts
Create actor link on contract creation
Signed-off-by: YingwenChen <yingwenchen@balena.io>
=> Create actor link on contract creation

package.json
=> Update graphile-worker from 0.12.2 to 0.13.0

lib/index.ts
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-default/pull/1174
- https://github.com/product-os/jellyfish-plugin-product-os/pull/824
- https://github.com/product-os/jellyfish-plugin-channels/pull/667
- https://github.com/product-os/jellyfish-plugin-typeform/pull/915
- https://github.com/product-os/jellyfish-plugin-github/pull/906
- https://github.com/product-os/jellyfish-plugin-flowdock/pull/489
- https://github.com/product-os/jellyfish-plugin-outreach/pull/659
- https://github.com/product-os/jellyfish-plugin-balena-api/pull/499
- https://github.com/product-os/jellyfish-plugin-front/pull/514
- https://github.com/product-os/jellyfish-plugin-discourse/pull/476
=> Remove contract exist check from insertCard

lib/contracts/index.ts, lib/contracts/relationship-any-is-creator-of-any.ts
=> Add creator relationship

package.json, test/integration/actions/action-create-event.spec.ts, test/integration/contracts/mixins/with-events.spec.ts, test/integration/execute.spec.ts, test/integration/index.spec.ts, test/integration/insert-card.spec.ts, test/integration/queue/index.spec.ts, test/integration/transformers.spec.ts
Signed-off-by: Ramiro Gonzalez <ramiro.gonzalez@balena.io>
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-default/pull/1157
- https://github.com/product-os/jellyfish-plugin-product-os/pull/815
- https://github.com/product-os/jellyfish-plugin-channels/pull/655
- https://github.com/product-os/jellyfish-plugin-typeform/pull/898
- https://github.com/product-os/jellyfish-plugin-flowdock/pull/478
- https://github.com/product-os/jellyfish-plugin-github/pull/890
- https://github.com/product-os/jellyfish-plugin-discourse/pull/465
- https://github.com/product-os/jellyfish-plugin-front/pull/503
- https://github.com/product-os/jellyfish-plugin-balena-api/pull/490
- https://github.com/product-os/jellyfish-plugin-outreach/pull/648
=> Update tests for relationships

lib/contracts/agent-settings.ts, lib/contracts/index.ts, lib/contracts/working-hours.spec.ts, lib/contracts/working-hours.ts
=> Add working hour contract

lib/actions/action-create-session.ts
=> Fix type import

lib/contracts/index.ts, lib/contracts/relationship-user-has-settings-working-hours.ts
=> Add user to working hours relationship

lib/index.ts
This change first checks to see if a contract needs to be updated before
replacing it on startup.
=> Don't blindly replace contracts on bootstrap

lib/triggers.ts
This change allows us to more quickly discard triggers that won't match
when evaluating link contract insertions.
The types on the trigger filter are compared to the types declared on
the link contract, and if they don't match we can safely exit the
trigger evaluation logic instead of having to query the kernel.
=> Use link from/to type as a heuristic when evaluating triggers

lib/index.ts
=> Don't insert the same contract multiple times during bootstrap

lib/index.ts
=> Ensure types are loaded from plugins before their instances

lib/test-utils.ts
=> Translate tests: Update worker cache after table restore

lib/test-utils.ts
=> Translate tests: Flush all for translate tests

lib/index.ts
Resolves https://github.com/product-os/jellyfish/issues/8733
=> Specify a long slug for creator links

package.json
=> Update autumndb to 20.1.12

lib/sync/instance.ts, package.json
=> Update axios from 0.26.1 to 0.27.2

.resinci.yml, jest.config.js, package.json, tsconfig.build.json, tsconfig.json, tslint.json
=> Drop @balena/jellyfish-config

.editorconfig, .github/workflows/publish-docs.yml, .gitignore, .npmrc
=> Drop more references to jellyfish-config

lib/index.ts
=> Fix incorrect comparison when setting type contract cache

lib/sync/instance.spec.ts, lib/sync/instance.ts, lib/sync/oauth.ts, lib/sync/pipeline.ts, package.json
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-default/pull/1208
- https://github.com/product-os/jellyfish-plugin-typeform/pull/942
- https://github.com/product-os/jellyfish-plugin-flowdock/pull/511
- https://github.com/product-os/jellyfish-plugin-github/pull/937
=> Drop bluebird

package.json
=> Upgrade to Jellyscript 7.1.0 that supports COUNT_BY

lib/contracts/index.ts, lib/contracts/loop-balena-io.ts, lib/contracts/loop-balenalabs.ts, lib/contracts/loop-company-os.ts, lib/contracts/loop-product-os.ts, lib/contracts/loop-team-os.ts, lib/contracts/role-loop.ts, lib/contracts/view-all-jellyfish-support-threads.ts, lib/index.ts, lib/types/contracts/index.ts
Bring in jellyfish-plugin-product-os as a prereq to bringing in
jellyfish-plugin-default.
=> Bring in plugin-product-os

lib/contracts/index.ts, lib/contracts/relationship-loop-has-thread.ts, lib/types/contracts/index.ts
=> Add relationship between loops and threads

lib/contracts/relationship-loop-has-channel.ts
Fixes https://github.com/product-os/jellyfish/issues/8852
=> Add relationship between loops and channels

lib/contracts/index.ts, lib/contracts/relationship-loop-has-sub-loop.ts
=> Add sub-loop relationship

lib/index.ts
=> Reduce verbosity of logging

lib/contracts/triggered-action-integration-import-event.ts, lib/types/contracts/index.ts
=> Add statuspage to translate sources

lib/contracts/triggered-action-integration-import-event.ts, lib/types/contracts/index.ts
Going the route of handling webhooks with triggered actions
=> Remove statuspage from translate sources

lib/contracts/role-user-external-support.ts, lib/types/contracts/index.ts, test/integration/contracts/role-user-external-support.spec.ts
=> Allow external support users to read but not write relationships

lib/types/contracts/index.ts, package.json
Update autumndb to version with interface generation alphabetization
fix, and regenerate type contract interfaces.
=> Update type contract interface definitions

lib/sync/pipeline.ts
=> Log references on failed evaluation

lib/actions/action-create-event.ts, test/integration/actions/action-create-event.spec.ts
This change pulls in logic from the Jellyfish UI that populates event metadata by parsing the message body.
This makes behaviour more consistent and testable, especially when interacting with Jellyfish using the client SDK or directly over http instead of through the UI.
The code was originally copied from here https://github.com/product-os/jellyfish/blob/v56.3.6/apps/ui/lib/services/helpers.ts#L971
=> action-create-event: Populate metadata extracted from message body

lib/actions/action-direct-message-subscription.ts, lib/actions/index.ts, lib/contracts/index.ts, lib/contracts/relationship-user-has-notification.ts, lib/contracts/thread.ts, lib/contracts/triggered-action-direct-message-subscription.ts, lib/index.ts, lib/subscriptions.ts, lib/types/contracts/thread.ts, test/integration/contracts/notification.spec.ts, test/integration/contracts/triggered-action-direct-message-subscription.spec.ts
=> Generate notification when mentioning a user

lib/contracts/index.ts, lib/contracts/relationship-org-has-thread.ts
=> Add relationship between orgs and threads

lib/contracts/index.ts, lib/contracts/relationship-org-has-loop.ts
=> Create relationship between orgs and loops

lib/contracts/index.ts
=> Correctly load loop/channel relationship

lib/contracts/index.ts, lib/contracts/relationship-thread-is-of-any.ts
=> Add relationship between thread and any contract

lib/index.ts, lib/subscriptions.ts
This change also improves logging for critical errors when generating notifications.
=> Only consider active groups in subscriptions

lib/contracts/notification.ts, lib/types/contracts/notification.ts
=> Add a status field to notifications

lib/contracts/improvement-default.md, lib/contracts/triggered-action-integration-import-event.ts
=> Remove Flowdock references

lib/actions/action-complete-password-reset.ts, lib/test-utils.ts, test/integration/actions/action-complete-password-reset.spec.ts, test/integration/actions/action-request-password-reset.spec.ts, test/integration/actions/action-send-first-time-login-link.spec.ts
=> Test utils: Use passed session when creating event

lib/contracts/thread.ts, test/integration/contracts/thread.spec.ts
=> Set the name of threads to the first message in it's timeline

lib/contracts/relationship-any-is-creator-of-any.ts, lib/contracts/relationship-create-is-attached-to-any.ts, lib/contracts/relationship-message-is-attached-to-any.ts, lib/contracts/relationship-thread-is-of-any.ts, lib/contracts/relationship-update-is-attached-to-any.ts, lib/contracts/relationship-whisper-is-attached-to-any.ts
=> Fix incorrect title metadata on a number of wildcard relationships

lib/contracts/thread.ts
=> Allow thread name to be null

lib/index.ts
The code to find dev/test contracts to skip in production was being
executed against the wrong set of contracts. Also, the role-user-test
contract is inserted by autumndb so trying to skip it here doesn't
make sense.
=> Fix skipped contracts on init

lib/contracts/milestone.ts
=> Allow users to manually set milestone status

lib/sync/instance.ts, lib/sync/sync-context.ts, test/unit/front_api_actor.spec.ts
Signed-off-by: Ramiro Gonzalez <ramiro.gonzalez@balena.io>
=> Clean up invalid API email addresses coming from Front

lib/types/index.ts, package.json, test/integration/contracts/action-request.spec.ts
See https://github.com/product-os/autumndb/pull/1462
=> Improve stream functionality and handling of links in streams

package.json
=> Update @balena/jellyfish-environment from 13.0.13 to 14.0.0

lib/contracts/index.ts, lib/contracts/relationship-improvement-is-attached-to-product.ts
=> Add improvement to product relationship

package.json, test/integration/actions/action-create-card.spec.ts, test/integration/actions/action-set-user-avatar.spec.ts
=> Add more operator tests

lib/actions/action-google-meet.ts, lib/index.ts
=> Export Google Meet creation functionality

package.json
=> Update autumndb from 22.2.87 to 22.2.95

.github/renovate.json, .github/workflows/codeql-analysis.yml, .prettierignore, .prettierrc, docker-compose.test.yml, docker-compose.yml, package.json, tsconfig.build.json, tsconfig.json, tslint.json
=> Dev: Use prettier for json/yml

package.json, test/unit/contracts/working-hours.spec.ts, test/unit/formulas.spec.ts, test/unit/index.spec.ts, test/unit/plugin/helpers.ts, test/unit/plugin/plugin-manager.spec.ts, test/unit/plugin/plugin.spec.ts, test/unit/queue/producer.spec.ts, test/unit/sync/index.spec.ts, test/unit/sync/instance.spec.ts, test/unit/sync/oauth.spec.ts, test/unit/sync/pipeline.spec.ts, test/unit/triggers.spec.ts, test/unit/utils.spec.ts
=> CI: Move all unit tests to test/unit

package.json
=> Update uuid from 8.3.2 to 9.0.0

lib/actions/action-broadcast.ts, lib/actions/action-complete-first-time-login.ts, lib/actions/action-complete-password-reset.ts, lib/actions/action-create-event.ts, lib/actions/action-create-session.ts, lib/actions/action-delete-card.ts, lib/actions/action-google-meet.ts, lib/actions/action-increment.ts, lib/actions/action-maintain-contact.ts, lib/actions/action-matchmake-task.ts, lib/actions/action-merge-draft-version.ts, lib/actions/action-request-password-reset.ts, lib/actions/action-send-first-time-login-link.ts, lib/actions/action-set-add.ts, lib/actions/action-set-password.ts, lib/actions/action-set-update.ts, lib/actions/action-set-user-avatar.ts, lib/actions/action-update-card.ts, lib/actions/utils.ts, test/integration/actions/action-send-first-time-login-link.spec.ts, test/integration/contracts/role-user-external-support.spec.ts, test/integration/index.spec.ts, test/integration/insert-card.spec.ts, test/integration/relationships.spec.ts
=> Use type cache when possible

.github/workflows/flowzone.yml, lib/sync/index.ts
=> Remove token requirement for valid event check

lib/index.ts, test/integration/insert-card.spec.ts
=> Reduce 'is creator of' link usage

lib/index.ts
=> Schedule actions even if previous attempt failed

lib/index.ts
=> Assert scheduled-action type

lib/sync/sync-context.ts, lib/triggers.ts
=> Expose query to sync context

lib/sync/instance.ts, lib/sync/types.ts
=> Add query function to sync interfaces

lib/actions/action-complete-first-time-login.ts, lib/actions/action-complete-password-reset.ts, lib/actions/action-create-session.ts, lib/actions/action-google-meet.ts, lib/actions/action-increment.ts, lib/actions/action-maintain-contact.ts, lib/actions/action-request-password-reset.ts, lib/actions/action-send-first-time-login-link.ts, lib/actions/action-set-add.ts, lib/actions/action-set-update.ts, lib/actions/action-set-user-avatar.ts
=> Reduce number of event creations/links

package.json
=> Update autumndb to v22.8.1

package.json
=> Update typescript to v5

package.json
=> Update nock from 13.2.9 to 13.3.0

lib/actions/mirror.ts, lib/queue/consumer.ts, lib/sync/index.ts, package.json, repo.yml
=> Remove jellyfish-metrics

package.json
=> Update bcrypt from 5.1.0 to 5.1.1

package.json
=> Update json-e to 4.5.3

package.json
=> Update @types/semver to 7.5.0

package.json
=> Update qs to 6.11.2

package.json
=> Update countries-and-timezones to 3.5.1

package.json
=> Update nock to 13.3.3

package.json
=> Update sinon to 15.2.0

package.json
=> Update just-permutations to 2.2.1

package.json
=> Remove unused @types/bluebird
