product-os/jellyfish-worker

package.json

See: https://github.com/product-os/jellyfish-plugin-default/pull/869.

Remove dev-only peer dependencies

---

lib/index.ts
lib/test-utils.ts
lib/utils.ts
test/integration/actions/action-create-card.spec.ts
test/integration/actions/action-create-event.spec.ts
test/integration/execute.spec.ts
test/integration/index.spec.ts
test/integration/insert-card.spec.ts
test/integration/triggers.spec.ts

---
Update `kernel` calls:
- `getCardById()` => `getContractById()`
- `getCardBySlug()` => `getContractBySlug()`
- `replaceCard()` => `replaceContract()`
We also need to update `WorkerContext` etc to have its exported function names to match, but that would be a breaking change that we can come back to later.

Switch to kernel contract function names

---

lib/sync/index.ts
lib/sync/types.ts

---
Make the `getFile()` integration function optional.

Make getFile optional

---

lib/index.ts
lib/plugin/plugin-manager.ts
lib/plugin/plugin.ts
lib/sync/index.ts
lib/test-utils.ts
package.json
test/integration/actions/action-set-add.spec.ts
test/integration/execute.spec.ts
test/integration/index.spec.ts
test/integration/insert-card.spec.ts
test/integration/subscriptions.spec.ts
test/integration/sync-context.spec.ts
test/integration/triggers.spec.ts

---
- Use `createUser()` and `createSession()` test utils provided `jellyfish-core` 
- Drop own `createUser()` and `createSession()` test util functions
- Fix a number of TS issues

Use core test utils for create user/session

---

lib/plugin/plugin.ts

Fix the plugin constructor accessing the wrong property in an action definition

---

lib/actions/action-create-card.ts
lib/actions/action-create-event.ts
lib/actions/action-create-session.ts
lib/actions/action-create-user.ts
lib/actions/action-set-add.ts
lib/actions/action-update-card.ts
lib/index.ts
lib/plugin/helpers.ts
lib/plugin/index.ts
lib/plugin/plugin-manager.spec.ts
lib/plugin/plugin-manager.ts
lib/plugin/plugin.spec.ts
lib/plugin/plugin.ts
lib/test-utils.ts
test/integration/insert-card.spec.ts

- Don't export the `Plugin` class. Plugins are now defined as `PluginDefinition` objects.
- Remove the ability to define contracts as functions.
- Remove custom mixins.
- Properly define the type for action contracts.

Simplify the plugin interface

---

lib/index.ts

---
Export `PluginManager` so consumers can instantiate and work with a plugin manager.

Export PluginManager

---

lib/sync/instance.ts

---
Adding back the ability to execute requests with querystrings. We had this before we switched from the deprecated `request` package to `axios` in https://github.com/product-os/jellyfish-worker/pull/1268. Found that it is used by `plugin-discourse` and seems like a useful option to keep around.

Allow querystring requests

---

lib/test-utils.ts

---
Speed up translate tests by executing `flush()` instead of `flushAll()` when processing requests. The original `test-harness` used `flush()` so I must have made a mistake when copying the logic/code over into `worker`. My bad.

Speed up translate test runner

---

package.json

Recent changes make the extra
jest flags unnecessary

Simplify test:integration npm script

---

lib/sync/oauth.spec.ts
lib/sync/oauth.ts

If a request to an external resource returns a failure code, the code
should be returned as-is. The axios behaviour is to throw on a status
code > 300, compared to the deprecated request package, which would just
return the status code in its callback params.
The rest of the code actually expects the 300+ error codes and even has
logic to handle them sanely.

Oauth: Fix bug where http request failures are not handled correctly

---

lib/index.ts
lib/sync/index.ts
lib/sync/instance.ts
lib/sync/types.ts

Previously, the `request` method incorrectly typed the `actor` parameter
as a boolean, when it's actually a string, and even worse, cast the
request options argument as `any`.
This change also exports useful types for use by integrations.

Sync: Improve type safety of SyncContext.request method

---

package.json
test/integration/insert-card.spec.ts

This change fixes a bug where formulas that have output dependent on
another formula field don't update correctly.
Fixes https://github.com/product-os/jellyfish-worker/issues/1360

Ensure that formulas are evaluated in the correct order 

---

package.json

As described in
https://github.com/product-os/jellyfish-worker/pull/1348/commits/b129cde1400bbc0eb61ef0a8adabb868828f105e
serialize-error is an esm module as of v9.x which will be a big lift for
us to support across our stack. The original PR didn't pin the version,
which meant that renovate auto-updated it.

Pin serialize-error to 8.x

---

lib/test-utils.ts
package.json
test/integration/subscriptions.spec.ts

---
- Bump `jellyfish-core` to v15.1.0
- Rename `createLink()` test utility to `createLinkThroughWorker()`
- `jellyfish-core` now supplies a basic `createLink()` test utility, but most times we will want to create links through the worker to ensure dynamically generated link-based triggered actions are triggered and executed

Bump jellyfish-core, replace createLink helper

---

.github/renovate.json

Ignoring for now as serialize-error has moved to ESM

Renovate: Ignore serialize-error bumps for now

---

lib/contracts/index.ts
lib/index.ts
lib/test-utils.ts

We should avoid exporting with default and
instead match other modules by exporting
a typed, named variable.
---
Marking this as a major change as the exported `CARDS` is replaced with `contracts`. Also, the structure of these exported variables are different even though the content is the same.
Testing with:
- https://github.com/product-os/jellyfish-plugin-github/pull/756
- https://github.com/product-os/jellyfish/pull/8233

Fix contract export

---

lib/actions/action-create-event.ts
lib/index.spec.ts
lib/index.ts
lib/plugin/plugin.ts
lib/sync/sync-context.ts
lib/test-utils.ts
lib/triggers.ts
lib/types.ts
lib/utils.ts
package.json
test/integration/actions/action-create-card.spec.ts
test/integration/actions/action-create-event.spec.ts
test/integration/actions/action-set-add.spec.ts
test/integration/execute.spec.ts
test/integration/index.spec.ts
test/integration/insert-card.spec.ts
test/integration/subscriptions.spec.ts
test/integration/trigger-updates.spec.ts
test/integration/triggers.spec.ts
test/integration/utils.spec.ts

The `jellyfish-core` package has been renamed to `autumndb`

Use autumndb instead of jellyfish-core

---

lib/index.ts
lib/test-utils.ts
test/integration/index.spec.ts

Add stream to keep the worker instance
up to date with type and triggered action
contracts as they are added to the system.
---
I'd like to deploy this myself as we should remove the type and triggered action portions of the same stream defined in `apps/server`.
Testing in https://github.com/product-os/jellyfish/pull/8410

Add type and triggered action stream

---

lib/index.spec.ts
lib/index.ts
lib/test-utils.ts
lib/transformers.spec.ts
lib/transformers.ts
lib/types.ts
test/integration/index.spec.ts
test/integration/insert-card.spec.ts

Update worker to be created with a list of plugins.
This means that all contracts provided by plugins
are inserted into the system when the worker starts.
Also allows us to add in the worker instance contract
update stream. A part of bringing the API codebase
into the worker.
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-default/pull/1079
- https://github.com/product-os/jellyfish-plugin-product-os/pull/776
- https://github.com/product-os/jellyfish-plugin-channels/pull/607
- https://github.com/product-os/jellyfish-plugin-typeform/pull/834
- https://github.com/product-os/jellyfish-plugin-flowdock/pull/408
- https://github.com/product-os/jellyfish-plugin-balena-api/pull/412
- …

Init worker with plugins

---

lib/index.spec.ts
lib/index.ts
lib/queue/index.ts
lib/queue/producer.spec.ts
lib/queue/producer.ts
lib/queue/types.ts
lib/test-utils.ts
lib/types.ts
lib/utils.ts
test/integration/actions/action-create-card.spec.ts
test/integration/actions/action-create-event.spec.ts
test/integration/execute.spec.ts
test/integration/index.spec.ts
test/integration/queue/events.spec.ts
test/integration/queue/index.spec.ts

Automatically enqueue any inserted action-request
type contracts. Drop support for manually enqueueing
action requests.
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-product-os/pull/780
- https://github.com/product-os/jellyfish-plugin-default/pull/1109
- https://github.com/product-os/jellyfish-plugin-flowdock/pull/439
- https://github.com/product-os/jellyfish-plugin-github/pull/845
- https://github.com/product-os/jellyfish-plugin-channels/pull/622
- https://github.com/product-os/jellyfish-plugin-typeform/pull/867
- https://github.com/product-os/jellyfish-plugin-outreach/pull/606
- https://github.com/product-os/jellyfish-plugin-balena-api/pull/444
- …

Enqueue inserted action requests

---

lib/plugin/helpers.ts
lib/sync/index.ts
lib/sync/instance.spec.ts
lib/sync/instance.ts
lib/sync/pipeline.ts
lib/sync/types.ts

- Remove extra parameter `provider` for running integration. Oauth credentials in user contract is stored in [`user.data.oauth[integration]`](https://github.com/product-os/jellyfish-worker/blob/6c93126aa385f5e0d5c242de14988383fdfca856/lib/sync/index.ts#L258-L295);
- Add slug to integration definition;

Add slug to integration definition

---

lib/sync/index.ts
lib/sync/sync-context.ts
lib/sync/types.ts

Pass an instance of SyncActionContext instead of
LogContext into the whoami() function to give
this function the ability to query the backend.

Pass SyncActionContext to whoami()

---

lib/sync/index.ts

Slug passed in sync.match contains version, so no need to add additional version.

Remove duplicate version from slug

---

lib/index.ts
lib/test-utils.ts
package.json
test/integration/index.spec.ts
test/integration/transformers.spec.ts

Because updates to transformers, triggers and types are infrequent,
streaming these contracts generates a lot of overhead. Switching to
a slow polling strategy should reduce load on the DB.
This change also adds a `stop()` method that can safely shutdown the
worker, waiting for jobs to finish and stopping the polling.
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-default/pull/1198
- https://github.com/product-os/jellyfish-plugin-channels/pull/681
- https://github.com/product-os/jellyfish-plugin-flowdock/pull/503
- https://github.com/product-os/jellyfish-plugin-typeform/pull/933

Switch to polling strategy for cached contracts

---

lib/triggers.ts

This PR covers a few more cases where we can safely reject the trigger without having to make a query to the database.

Improve heuristics in trigger validation

---

lib/contracts/triggered-action-matchmake-task.ts

By specifying the contract type that the trigger expands, we can use
heuristics to reduce unnecessary queries to the DB.

Improve performance of task matchmaking trigger

---

lib/actions/action-create-session.ts

Make sure the `user` and its `authorization-password` contracts are active before creating a session

---

lib/actions/action-bootstrap-channel.ts
lib/actions/index.ts
lib/contracts/agent-channel-settings.ts
lib/contracts/channel.ts
lib/contracts/index.ts
lib/contracts/relationship-channel-has-agent-user.ts
lib/contracts/relationship-channel-has-settings-agent-channel-settings.ts
lib/contracts/relationship-user-has-settings-agent-channel-settings.ts
lib/contracts/relationship-view-is-attached-to-channel.ts
lib/contracts/triggered-action-bootstrap-channel.ts
lib/types.ts
package.json

Bring in all contracts and actions defined by plugin-channels
---
This is needed for support v2 matchmaking as its logic needs to be able to reference agents' channel settings (opt-in etc). Also, channels should just be a first class citizen and not defined in a plugin. If/when this is merged, we can stop using and archive `jellyfish-plugin-channels`.

Bring in channels

---

lib/index.ts
lib/triggers.ts
test/integration/relationships.spec.ts

Fixes a bug where some materialized fields won't be calculated correctly.
What happens is that because we now use relationships to create the triggered actions, used to process materialized fields, if you insert the relationship after the type then the triggered action won't be generated.  The triggered actions only get generated when a type contract is inserted.
We need to changes this so that the formulas will get parsed and the appropriate triggered actions generated when a new relationship is inserted.

Fix bug where triggers are not recalculated when a relationship is added

---

lib/contracts/index.ts
lib/contracts/triggered-action-org-creation-membership.ts
lib/index.ts
lib/triggers.ts
test/integration/actions/action-send-first-time-login-link.spec.ts
test/integration/membership.spec.ts

This change adds a check to see if the user is an org member before allowing link creation between user and org.
This link is used to calculate marker permissions so needs to be specially protected.
It also closes some other holes that would affect the ability to "join" an org.
- Users can no longer create a link between a user and an org if they
are not a member or creator of the org
- When a user creates an org, they automatically become a member of the org
- Users can no longer create "was created by" links manually, as this could be used to bypass org creator validation
Note: This is a temporary solution until we have a better way to handle this. Once we are able to distinctly permission writes in AutumnDB, we can remove this.
Signed-off-by: Lucian Buzzo …

Only allow org members to add other users to an org

---

lib/actions/action-update-card.ts
test/integration/actions/action-update-card.spec.ts
test/integration/contracts/role-user-community.spec.ts
test/integration/contracts/role-user-external-support.spec.ts

Don't allow normal users to update other user contracts. user-admin
and users with operator role are allowed to edit other user contracts.
***
Testing with:
- https://github.com/product-os/jellyfish/pull/8916
- https://github.com/product-os/jellyfish-plugin-typeform/pull/979

Lock down user contract updates

---

lib/index.ts

When loading default contracts into the worker, ensure they are intialized in the same way that contracts loaded from plugins are. This sets the contract up with sane default fields and a uiSchema reset.

Initialize default contracts before inserting them

---

test/integration/insert-card.spec.ts

This is part of the renaming of the relationship
from `was built into` to `was transformed to`.
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>

Update integration tests to use `was transformed to`.

---

lib/actions/action-create-card.ts
lib/index.ts
lib/types/index.ts
test/integration/actions/action-create-card.spec.ts

Add the ability to create links between the contract being
created with action-create-card and other pre-existing contracts.

Add option to create links with action-create-card

---

lib/actions/action-create-card.ts
lib/index.ts
lib/subscriptions.ts
lib/test-utils.ts

When generating notifications, distribute the work across the queue

Distribute notification generation on the queue

---

lib/subscriptions.ts
test/integration/contracts/notification.spec.ts

This fixes a bug where the whisper type was not checked correctly, and
a notification would not be generated if there was a mention on a whisper.

Generate notifications when a user is mentioned in a whisper

---

lib/sync/instance.ts
lib/sync/sync-context.ts
lib/sync/types.ts
test/integration/sync-context.spec.ts

Add a new function for searching for contracts by mirror IDs using
an enum as a more efficient alternative to the pattern search option
provided by getElementByMirrorId.

Add getElementByMirrorIds enum query function

---

lib/errors.ts
lib/sync/index.ts
lib/sync/sync-action-context-retry-wrapper.ts
lib/sync/sync-context.ts

Signed-off-by: Ramiro Gonzalez <ramiro.gonzalez@balena.io>

Make worker use a SyncContext that retries queries that timeout

---

lib/actions/action-create-card.ts
lib/actions/action-update-card.ts

There is no need to attach create and update contracts to external-event contracts. This only results in the system creating unnecessary extra records in the database.
---
Testing with:
- https://github.com/product-os/jellyfish-plugin-typeform/pull/1232

Stop creating creates/updates for external-events

---

lib/index.ts

Use privileged session to insert action-request contracts for future execution as non-privileged sessions are not allowed to create action-request contracts.

Schedule action requests with correct session

---

lib/contracts/scheduled-action.ts
lib/index.ts
lib/types/contracts/scheduled-action.ts

Update options necessary to run scheduled actions, making them more
flexible so they can be used with more actions.

Make scheduled-actions more flexible
